[package]
name = "shadowsocks-rs"
version = "0.6.0"
authors = ["cssivision <cssivision@gmail.com>"]
license = "MIT"
repository = "https://github.com/cssivision/shadowsocks-rs"
homepage = "https://github.com/cssivision/shadowsocks-rs"
description = "personal port of shadowsocks in rust."
readme = "README.md"
edition = "2018"

[lib]
name = "shadowsocks"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "0.4"
env_logger = "0.7"
getopts = "0.2"
openssl = "0.10"
rand = "0.8"
md5 = "0.3"
futures-util = "0.3"
awak = "0.2"
c-ares-resolver = "7.1"
once_cell = "1.4"
anyhow = "1.0"
parking_lot = "0.11"
