[package]
name = "shadowsocks-rs"
version = "0.4.2"
authors = ["cssivision <cssivision@gmail.com>"]
license = "MIT"
repository = "https://github.com/cssivision/shadowsocks-rs"
homepage = "https://github.com/cssivision/shadowsocks-rs"
description = "personal port of shadowsocks in rust."
readme = "README.md"
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "0.4"
env_logger = "0.7"
getopts = "0.2"
openssl = "0.10"
rand = "0.7"
md5 = "0.3"
tokio = { version = "0.2", features = ["full"] }
futures = { version = "0.3", features = ["thread-pool", "alloc"] }
lazy_static = "1.0"
num_cpus = "1.0"
# trust-dns-resolver = { git = "https://github.com/bluejekyll/trust-dns.git" }
