[package]
name = "looli-rs"
version = "0.1.0"
authors = ["cssivision <cssivision@gmail.com>"]
license = "MIT"
repository = "https://github.com/cssivision/looli-rs"
homepage = "https://github.com/cssivision/looli-rs"
description = "personal simple proxy in rust."
readme = "README.md"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"