[package]
name = "shadowsocks-rs"
version = "0.1.0"
authors = ["cssivision <cssivision@gmail.com>"]
license = "MIT"
repository = "https://github.com/cssivision/shadowsocks-rs"
homepage = "https://github.com/cssivision/shadowsocks-rs"
description = "personal port of shadowsocks in rust."
readme = "README.md"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-socks5 = "0.1.4"
trust-dns-resolver = "0.5"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
log = "0.3"
env_logger = "0.3"
getopts = "0.2"
openssl = "0.9"
rand = "0.3"