[package]
name = "shadowsocks-rs"
version = "0.2.5"
authors = ["cssivision <cssivision@gmail.com>"]
license = "MIT"
repository = "https://github.com/cssivision/shadowsocks-rs"
homepage = "https://github.com/cssivision/shadowsocks-rs"
description = "personal port of shadowsocks in rust."
readme = "README.md"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
trust-dns-resolver = { git = "https://github.com/bluejekyll/trust-dns" }
tokio-io = "0.1"
log = "0.3"
env_logger = "0.3"
getopts = "0.2"
openssl = "0.10"
rand = "0.3"
md5 = "0.3"
tokio = "0.1"
futures = "0.1"
tokio-timer = "0.2"
lazy_static = "1.0"
