[[server]]
local_addr = "127.0.0.1:9006"
password = "password"
method = "aes-128-cfb"

[[client]]
local_addr = "127.0.0.1:6009"
server_addr = "127.0.0.1:9006"
password = "password"
method = "aes-128-cfb"
